/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nandocode
 */
public class Main extends javax.swing.JFrame {

    private int elementoMostrado = -1;
    Agenda lista = new Agenda();

    /**
     * Creates new form Main
     */
    public Main() {

        initComponents();
        lblMensajeAgendaVacia.setVisible(false);
        actualizacion();
        JP_BotonesAgregar.setVisible(false);

        this.setLocationRelativeTo(null);
    }

    private void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea cerrar la aplicacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }
    }

    private void mensajesJOption(String mensaje, String titulo, int tipoMensaje, Icon icono) {

        JOptionPane.showMessageDialog(this, mensaje, titulo, tipoMensaje, icono);

    }

    public final void actualizacion() {
        if (lista.vacia()) {
            btnEliminar.setEnabled(false);
            btnBuscar.setEnabled(false);
            btnAdelante.setEnabled(false);
            btnUltimoElemnto.setEnabled(false);
            //JP_BotonesAgregar.setVisible(false);
            lblMensajeAgendaVacia.setVisible(true);

        } else {
            btnEliminar.setEnabled(true);
            btnBuscar.setEnabled(true);
            btnAdelante.setEnabled(true);
            btnUltimoElemnto.setEnabled(true);
            lblMensajeAgendaVacia.setVisible(false);

        }
        elementoMostrado = -1;
        //txtNumElementos.setText(String.valueOf(lista.getIndice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        JP_BotonesAgregar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnUltimoElemnto = new javax.swing.JButton();
        btnPrimerElemento = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        lblMensajeAgendaVacia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AGENDA");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 73, 73));

        txtTelefono.setEditable(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 300, 40));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar.png"))); // NOI18N
        btnAgregar.setToolTipText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 73, 73));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 73, 73));

        jLabel1.setText("EDAD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 40, 30));

        jLabel2.setText("FOLIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 40));

        jLabel3.setText("TELEFONO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 40));

        txtFolio.setEditable(false);
        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });
        jPanel1.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, 40));

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 300, 40));

        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 40));

        txtEdad.setEditable(false);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, 40));

        jLabel5.setText("APELLIDOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 40));

        txtApellidos.setEditable(false);
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 300, 40));

        btnGuardar.setBackground(new java.awt.Color(16, 125, 20));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardar.setForeground(java.awt.Color.white);
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(193, 36, 7));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(java.awt.Color.white);
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_BotonesAgregarLayout = new javax.swing.GroupLayout(JP_BotonesAgregar);
        JP_BotonesAgregar.setLayout(JP_BotonesAgregarLayout);
        JP_BotonesAgregarLayout.setHorizontalGroup(
            JP_BotonesAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BotonesAgregarLayout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );
        JP_BotonesAgregarLayout.setVerticalGroup(
            JP_BotonesAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BotonesAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_BotonesAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JP_BotonesAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 230, -1));

        btnUltimoElemnto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-fin-48.png"))); // NOI18N
        btnUltimoElemnto.setToolTipText("Ultimo elemento");
        btnUltimoElemnto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoElemntoActionPerformed(evt);
            }
        });
        jPanel1.add(btnUltimoElemnto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 48, 48));

        btnPrimerElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-saltar-a-inicio-48.png"))); // NOI18N
        btnPrimerElemento.setToolTipText("Primer Elemento");
        btnPrimerElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerElementoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrimerElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 48, 48));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-atrás-48.png"))); // NOI18N
        btnAtras.setToolTipText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 48, 48));

        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-chebrón-hacia-la-derecha-48.png"))); // NOI18N
        btnAdelante.setToolTipText("Adelante");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 48, 48));

        lblMensajeAgendaVacia.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblMensajeAgendaVacia.setForeground(new java.awt.Color(255, 0, 22));
        lblMensajeAgendaVacia.setText("Agenda Vacia");
        lblMensajeAgendaVacia.setToolTipText("");
        jPanel1.add(lblMensajeAgendaVacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 524, 471));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFolioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!txtFolio.getText().equals("") && !txtNombre.getText().equals("")
                && !txtApellidos.getText().equals("")
                && !txtTelefono.getText().equals("") && !txtEdad.getText().equals("")) {

            Cliente cliente = new Cliente();
            cliente.setFolio(Integer.parseInt(txtFolio.getText()));
            cliente.setNombre(txtNombre.getText());
            cliente.setApellidos(txtApellidos.getText());
            cliente.setTelefono(Long.parseLong(txtTelefono.getText()));
            cliente.setEdad(Integer.parseInt(txtEdad.getText()));
            if (!(lista.existeFolio(Integer.parseInt(txtFolio.getText())))) {
                if (lista.addLista(cliente)) {
                    // Mensaje de exito
                    mensajesJOption("Se ingreso exitosamente", "Exelnte", JOptionPane.INFORMATION_MESSAGE,
                            new ImageIcon("src/recursos/exito.png"));
                    JP_BotonesAgregar.setVisible(false);
                    txtFolio.setEditable(false);
                    txtNombre.setEditable(false);
                    txtApellidos.setEditable(false);
                    txtTelefono.setEditable(false);
                    txtEdad.setEditable(false);
                    txtFolio.setText("");
                    txtNombre.setText("");
                    txtApellidos.setText("");
                    txtTelefono.setText("");
                    txtEdad.setText("");
                }
            } else {
                mensajesJOption("Folio Repetido ", "ERROR", JOptionPane.ERROR_MESSAGE,
                        null);
            }
            actualizacion();
        } else {
            mensajesJOption("No deje campos vacios", "ERROR", JOptionPane.ERROR_MESSAGE,
                    null);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        JP_BotonesAgregar.setVisible(false);
        txtFolio.setEditable(false);
        txtNombre.setEditable(false);
        txtApellidos.setEditable(false);
        txtTelefono.setEditable(false);
        txtEdad.setEditable(false);
        mensajesJOption("Registro Cancelado", "Cancelado", JOptionPane.ERROR_MESSAGE,
                null);
        txtFolio.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtEdad.setText("");

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (lista.getIndice() < 9) {
            txtFolio.setText("");
            txtNombre.setText("");
            txtApellidos.setText("");
            txtTelefono.setText("");
            txtEdad.setText("");

            JP_BotonesAgregar.setVisible(true);
            txtFolio.setEditable(true);
            txtFolio.requestFocus();
            txtNombre.setEditable(true);
            txtApellidos.setEditable(true);
            txtTelefono.setEditable(true);
            txtEdad.setEditable(true);
        }else{
            lblMensajeAgendaVacia.setText("Ajenda llena ");
            lblMensajeAgendaVacia.setVisible(true);
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        String seleccion = JOptionPane.showInputDialog(
                this,
                "Numero de Folio ", "ELIMINAR",
                JOptionPane.DEFAULT_OPTION);  // el icono sera un iterrogante
        if (!(seleccion == null)) {
            if (!seleccion.equals("") && seleccion.matches("[0-9]*")) {
                if (!lista.eliminarPersona(Integer.parseInt(seleccion))) {
                    mensajesJOption("Folio no encontrado",
                            "ERROR", JOptionPane.ERROR_MESSAGE, null);
                } else {
                    mensajesJOption("Se Elimino exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE,
                            new ImageIcon("src/recursos/exito.png"));
                    txtFolio.setText("");
                    txtNombre.setText("");
                    txtApellidos.setText("");
                    txtTelefono.setText("");
                    txtEdad.setText("");
                    lblMensajeAgendaVacia.setVisible(false);
                    lblMensajeAgendaVacia.setText("Ajenda Vacia ");
                    actualizacion();
                }

            } else {
                mensajesJOption("> No deje el campo vacio \n > No ingrese letras",
                        "ERROR", JOptionPane.ERROR_MESSAGE, null);
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        // TODO add your handling code here:
        String seleccion = JOptionPane.showInputDialog(
                this,
                "Numero de Folio ", "Buscar",
                JOptionPane.DEFAULT_OPTION);

        if (!(seleccion == null)) {
            if (!seleccion.equals("") && seleccion.matches("[0-9]*")) {

                int indice = lista.buscarPersona(Integer.parseInt(seleccion));
                if (indice != -1) {

                    Cliente envio = lista.itemAgenda(indice);

                    txtFolio.setText(String.valueOf(envio.getFolio()));
                    txtNombre.setText(envio.getNombre());
                    txtApellidos.setText(envio.getApellidos());
                    txtTelefono.setText(String.valueOf(envio.getTelefono()));
                    txtEdad.setText(String.valueOf(envio.getEdad()));
                    actualizacion();
                    elementoMostrado = indice;
                } else {
                    mensajesJOption(" Folio no encontrado",
                            "ERROR", JOptionPane.ERROR_MESSAGE, null);

                }
            } else {
                mensajesJOption("> No deje el campo vacio \n > No ingrese letras",
                        "ERROR", JOptionPane.ERROR_MESSAGE, null);
            }
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();

        if (elementoMostrado < lista.getIndice()) {
            cliente = lista.itemAgenda(elementoMostrado + 1);
            elementoMostrado = elementoMostrado + 1;
            txtFolio.setText(String.valueOf(cliente.getFolio()));
            txtNombre.setText(cliente.getNombre());
            txtApellidos.setText(cliente.getApellidos());
            txtTelefono.setText(String.valueOf(cliente.getTelefono()));
            txtEdad.setText(String.valueOf(cliente.getEdad()));

        } else {

        }


    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        Cliente cliente;

        if (elementoMostrado - 1 >= 0) {
            cliente = lista.itemAgenda(elementoMostrado - 1);
            elementoMostrado = elementoMostrado - 1;
            txtFolio.setText(String.valueOf(cliente.getFolio()));
            txtNombre.setText(cliente.getNombre());
            txtApellidos.setText(cliente.getApellidos());
            txtTelefono.setText(String.valueOf(cliente.getTelefono()));
            txtEdad.setText(String.valueOf(cliente.getEdad()));

        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnUltimoElemntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoElemntoActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        cliente = lista.itemAgenda(lista.getIndice());
        txtFolio.setText(String.valueOf(cliente.getFolio()));
        txtNombre.setText(cliente.getNombre());
        txtApellidos.setText(cliente.getApellidos());
        txtTelefono.setText(String.valueOf(cliente.getTelefono()));
        txtEdad.setText(String.valueOf(cliente.getEdad()));
        elementoMostrado = lista.getIndice();
    }//GEN-LAST:event_btnUltimoElemntoActionPerformed

    private void btnPrimerElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerElementoActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        if (!lista.vacia()) {
            cliente = lista.itemAgenda(0);
            elementoMostrado = 0;
            txtFolio.setText(String.valueOf(cliente.getFolio()));
            txtNombre.setText(cliente.getNombre());
            txtApellidos.setText(cliente.getApellidos());
            txtTelefono.setText(String.valueOf(cliente.getTelefono()));
            txtEdad.setText(String.valueOf(cliente.getEdad()));

        }

    }//GEN-LAST:event_btnPrimerElementoActionPerformed

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:

        char key = evt.getKeyChar();
        if (txtEdad.getText().length() >= 3) {
            evt.consume();

        }
        if (((key < '0') || (key > '9'))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!((key < '0') || (key > '9'))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!((key < '0') || (key > '9'))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (txtTelefono.getText().length() >= 10) {
            evt.consume();

        }
        if (((key < '0') || (key > '9'))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();

        if (txtFolio.getText().length() >= 5) {
            evt.consume();

        }
        if (((key < '0') || (key > '9'))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFolioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_BotonesAgregar;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPrimerElemento;
    private javax.swing.JButton btnUltimoElemnto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensajeAgendaVacia;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
